name: Build LaTeX document
on:
  push:
    tags:
      - "*"
jobs:
  build_latex:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: src
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v1
      - name: Accept mscorefonts-eula
        shell: bash
        run: echo ttf-mscorefonts-installer msttcorefonts/accepted-mscorefonts-eula select true | sudo debconf-set-selections
      - name: Install Times New Roman font
        run: sudo apt-get install -y ttf-mscorefonts-installer
      - name: Install Luatex
        run: sudo apt-get install -y texlive texlive-luatex texlive-latex-base texlive-latex-extra
      - name: Compile LaTeX document
        run: lualatex Arroyo.tex
      - name: Publish
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: src/Arroyo.pdf

        